# -*- coding: utf-8 -*-
"""Untitled56.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h4-jyIBP6wQY5uHwOF4twR-aYKtMkyvf
"""

import cv2
from skimage.metrics import structural_similarity as ssim

def compute_ssim(image1_path, image2_path):
    img1 = cv2.imread(image1_path, cv2.IMREAD_GRAYSCALE)
    img2 = cv2.imread(image2_path, cv2.IMREAD_GRAYSCALE)

    img2 = cv2.resize(img2, (img1.shape[1], img1.shape[0]))
    score = ssim(img1, img2)
    print(f"SSIM: {score:.4f}")

# Example usage
compute_ssim("your_original_image_path_here.png", "your_generated_image_path here.png") #Replace with your respective original and generated image path